/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

/// BulkMutateAListOfIssuesRequestStatusDetails : Additional details about the resolution. Valid values are `\"inRelease\"`, `\"inNextRelease\"`, `\"inCommit\"`, `\"ignoreDuration\"`, `\"ignoreCount\"`, `\"ignoreWindow\"`, `\"ignoreUserCount\"`, and `\"ignoreUserWindow\"`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkMutateAListOfIssuesRequestStatusDetails {
    #[serde(rename = "inRelease", skip_serializing_if = "Option::is_none")]
    pub in_release: Option<String>,
    #[serde(rename = "inNextRelease", skip_serializing_if = "Option::is_none")]
    pub in_next_release: Option<bool>,
    #[serde(rename = "inCommit", skip_serializing_if = "Option::is_none")]
    pub in_commit: Option<String>,
    #[serde(rename = "ignoreDuration", skip_serializing_if = "Option::is_none")]
    pub ignore_duration: Option<i32>,
    #[serde(rename = "ignoreCount", skip_serializing_if = "Option::is_none")]
    pub ignore_count: Option<i32>,
    #[serde(rename = "ignoreWindow", skip_serializing_if = "Option::is_none")]
    pub ignore_window: Option<i32>,
    #[serde(rename = "ignoreUserCount", skip_serializing_if = "Option::is_none")]
    pub ignore_user_count: Option<i32>,
    #[serde(rename = "ignoreUserWindow", skip_serializing_if = "Option::is_none")]
    pub ignore_user_window: Option<i32>,
}

impl BulkMutateAListOfIssuesRequestStatusDetails {
    /// Additional details about the resolution. Valid values are `\"inRelease\"`, `\"inNextRelease\"`, `\"inCommit\"`, `\"ignoreDuration\"`, `\"ignoreCount\"`, `\"ignoreWindow\"`, `\"ignoreUserCount\"`, and `\"ignoreUserWindow\"`.
    pub fn new() -> BulkMutateAListOfIssuesRequestStatusDetails {
        BulkMutateAListOfIssuesRequestStatusDetails {
            in_release: None,
            in_next_release: None,
            in_commit: None,
            ignore_duration: None,
            ignore_count: None,
            ignore_window: None,
            ignore_user_count: None,
            ignore_user_window: None,
        }
    }
}


