/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkMutateAListOfIssues200Response {
    #[serde(rename = "isPublic")]
    pub is_public: bool,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "statusDetails")]
    pub status_details: serde_json::Value,
}

impl BulkMutateAListOfIssues200Response {
    pub fn new(
        is_public: bool,
        status: Status,
        status_details: serde_json::Value,
    ) -> BulkMutateAListOfIssues200Response {
        BulkMutateAListOfIssues200Response {
            is_public,
            status,
            status_details,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "resolved")]
    Resolved,
    #[serde(rename = "unresolved")]
    Unresolved,
    #[serde(rename = "ignored")]
    Ignored,
}

impl Default for Status {
    fn default() -> Status {
        Self::Resolved
    }
}
