/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkMutateAListOfIssuesRequest {
    /// The new status for the issues. Valid values are `\"resolved\"`, `\"resolvedInNextRelease\"`, `\"unresolved\"`, and `\"ignored\"`.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "statusDetails", skip_serializing_if = "Option::is_none")]
    pub status_details: Option<Box<crate::models::BulkMutateAListOfIssuesRequestStatusDetails>>,
    /// The number of minutes to ignore this issue.
    #[serde(rename = "ignoreDuration", skip_serializing_if = "Option::is_none")]
    pub ignore_duration: Option<i32>,
    /// Sets the issue to public or private.
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    /// Allows to merge or unmerge different issues.
    #[serde(rename = "merge", skip_serializing_if = "Option::is_none")]
    pub merge: Option<bool>,
    /// The actor id (or username) of the user or team that should be assigned to this issue.
    #[serde(rename = "assignedTo", skip_serializing_if = "Option::is_none")]
    pub assigned_to: Option<String>,
    /// In case this API call is invoked with a user context this allows changing of the flag that indicates if the user has seen the event.
    #[serde(rename = "hasSeen", skip_serializing_if = "Option::is_none")]
    pub has_seen: Option<bool>,
    /// In case this API call is invoked with a user context this allows changing of the bookmark flag.
    #[serde(rename = "isBookmarked", skip_serializing_if = "Option::is_none")]
    pub is_bookmarked: Option<bool>,
}

impl BulkMutateAListOfIssuesRequest {
    pub fn new() -> BulkMutateAListOfIssuesRequest {
        BulkMutateAListOfIssuesRequest {
            status: None,
            status_details: None,
            ignore_duration: None,
            is_public: None,
            merge: None,
            assigned_to: None,
            has_seen: None,
            is_bookmarked: None,
        }
    }
}
