/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAnExternalIssueRequest {
    /// The ID of the Sentry issue to link the external issue to.
    #[serde(rename = "issueId")]
    pub issue_id: i32,
    /// The URL of the external service to link the issue to.
    #[serde(rename = "webUrl")]
    pub web_url: String,
    /// The external service's project.
    #[serde(rename = "project")]
    pub project: String,
    /// A unique identifier of the external issue.
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl CreateAnExternalIssueRequest {
    pub fn new(
        issue_id: i32,
        web_url: String,
        project: String,
        identifier: String,
    ) -> CreateAnExternalIssueRequest {
        CreateAnExternalIssueRequest {
            issue_id,
            web_url,
            project,
            identifier,
        }
    }
}
