/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateANewProjectRequest {
    /// The name for the new project.
    #[serde(rename = "name")]
    pub name: String,
    /// Optional slug for the new project. If not provided a slug is generated from the name.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}

impl CreateANewProjectRequest {
    pub fn new(name: String) -> CreateANewProjectRequest {
        CreateANewProjectRequest {
            name,
            slug: None,
        }
    }
}


