/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateANewClientKeyRequest {
    /// The name for the new key.
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateANewClientKeyRequest {
    pub fn new(name: String) -> CreateANewClientKeyRequest {
        CreateANewClientKeyRequest { name }
    }
}
