/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateANewReleaseForAnOrganizationRequest {
    /// A version identifier for this release. Can be a version number, a commit hash, etc.
    #[serde(rename = "version")]
    pub version: String,
    /// An optional commit reference. This is useful if a tagged version has been provided.
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    /// A URL that points to the release. This can be the path to an online interface to the source code for instance
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// A list of project slugs that are involved in this release.
    #[serde(rename = "projects")]
    pub projects: Vec<String>,
    /// An optional date that indicates when the release went live. If not provided the current time is assumed.
    #[serde(rename = "dateReleased", skip_serializing_if = "Option::is_none")]
    pub date_released: Option<String>,
    /// An optional list of commit data to be associated with the release. Commits must include parameters `id` (the SHA of the commit), and can optionally include `repository`, `message`, `patch_set`, `author_name`, `author_email`, and `timestamp`.
    #[serde(rename = "commits", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Vec<crate::models::CreateANewReleaseForAnOrganizationRequestCommitsInner>>,
    /// An optional way to indicate the start and end commits for each repository included in a release. Head commits must include parameters `repository` and `commit` (the HEAD sha). They can optionally include `previousCommit` (the sha of the HEAD of the previous release), which should be specified if this is the first time you've sent commit data. `commit` may contain a range in the form of `previousCommit..commit`.
    #[serde(rename = "refs", skip_serializing_if = "Option::is_none")]
    pub refs: Option<Vec<crate::models::CreateANewReleaseForAnOrganizationRequestRefsInner>>,
}

impl CreateANewReleaseForAnOrganizationRequest {
    pub fn new(
        version: String,
        projects: Vec<String>,
    ) -> CreateANewReleaseForAnOrganizationRequest {
        CreateANewReleaseForAnOrganizationRequest {
            version,
            r#ref: None,
            url: None,
            projects,
            date_released: None,
            commits: None,
            refs: None,
        }
    }
}
