/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateANewDeployForAnOrganizationRequest {
    /// The environment you're deploying to.
    #[serde(rename = "environment")]
    pub environment: String,
    /// The optional URL that points to the deploy.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The optional name of the deploy.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The optional list of projects to deploy.
    // #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    // TODO: fix this type
    // pub projects: Option<crate::models::Array>,
    /// An optional date that indicates when the deploy started.
    #[serde(rename = "dateStarted", skip_serializing_if = "Option::is_none")]
    pub date_started: Option<String>,
    /// An optional date that indicates when the deploy ended. If not provided, the current time is used.
    #[serde(rename = "dateFinished", skip_serializing_if = "Option::is_none")]
    pub date_finished: Option<String>,
}

impl CreateANewDeployForAnOrganizationRequest {
    pub fn new(environment: String) -> CreateANewDeployForAnOrganizationRequest {
        CreateANewDeployForAnOrganizationRequest {
            environment,
            url: None,
            name: None,
            // projects: None,
            date_started: None,
            date_finished: None,
        }
    }
}
