/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAnExternalIssue200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "issueId")]
    pub issue_id: String,
    #[serde(rename = "serviceType")]
    pub service_type: String,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "webUrl")]
    pub web_url: String,
}

impl CreateAnExternalIssue200Response {
    pub fn new(id: String, issue_id: String, service_type: String, display_name: String, web_url: String) -> CreateAnExternalIssue200Response {
        CreateAnExternalIssue200Response {
            id,
            issue_id,
            service_type,
            display_name,
            web_url,
        }
    }
}


