/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAProjectSClientKeys200ResponseInner {
    #[serde(rename = "browserSdk")]
    pub browser_sdk: Box<crate::models::ListAProjectSClientKeys200ResponseInnerBrowserSdk>,
    #[serde(rename = "browserSdkVersion")]
    pub browser_sdk_version: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(rename = "dsn")]
    pub dsn: Box<crate::models::ListAProjectSClientKeys200ResponseInnerDsn>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "projectId")]
    pub project_id: i32,
    #[serde(rename = "public")]
    pub public: String,
    #[serde(rename = "rateLimit", deserialize_with = "Option::deserialize")]
    pub rate_limit: Option<String>,
    #[serde(rename = "secret")]
    pub secret: String,
}

impl ListAProjectSClientKeys200ResponseInner {
    pub fn new(
        browser_sdk: crate::models::ListAProjectSClientKeys200ResponseInnerBrowserSdk,
        browser_sdk_version: String,
        date_created: String,
        dsn: crate::models::ListAProjectSClientKeys200ResponseInnerDsn,
        id: String,
        is_active: bool,
        label: String,
        name: String,
        project_id: i32,
        public: String,
        rate_limit: Option<String>,
        secret: String,
    ) -> ListAProjectSClientKeys200ResponseInner {
        ListAProjectSClientKeys200ResponseInner {
            browser_sdk: Box::new(browser_sdk),
            browser_sdk_version,
            date_created,
            dsn: Box::new(dsn),
            id,
            is_active,
            label,
            name,
            project_id,
            public,
            rate_limit,
            secret,
        }
    }
}
