/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAnOrganizationSIntegrationPlatformInstallations200ResponseInner {
    #[serde(rename = "app")]
    pub app: Box<crate::models::ListAnOrganizationSIntegrationPlatformInstallations200ResponseInnerApp>,
    #[serde(rename = "organization")]
    pub organization: Box<crate::models::ListAnOrganizationSIntegrationPlatformInstallations200ResponseInnerOrganization>,
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl ListAnOrganizationSIntegrationPlatformInstallations200ResponseInner {
    pub fn new(
        app: crate::models::ListAnOrganizationSIntegrationPlatformInstallations200ResponseInnerApp,
        organization: crate::models::ListAnOrganizationSIntegrationPlatformInstallations200ResponseInnerOrganization,
        uuid: String,
        status: String,
    ) -> ListAnOrganizationSIntegrationPlatformInstallations200ResponseInner {
        ListAnOrganizationSIntegrationPlatformInstallations200ResponseInner {
            app: Box::new(app),
            organization: Box::new(organization),
            uuid,
            status,
        }
    }
}
