/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAnOrganizationSPaginatedTeams200Response {
    #[serde(rename = "schemas", skip_serializing_if = "Option::is_none")]
    pub schemas: Option<Vec<String>>,
    #[serde(rename = "totalResults")]
    pub total_results: i32,
    #[serde(rename = "itemsPerPage")]
    pub items_per_page: i32,
    #[serde(rename = "startIndex")]
    pub start_index: i32,
    #[serde(rename = "Resources")]
    pub resources: Vec<crate::models::ListAnOrganizationSPaginatedTeams200ResponseResourcesInner>,
}

impl ListAnOrganizationSPaginatedTeams200Response {
    pub fn new(
        total_results: i32,
        items_per_page: i32,
        start_index: i32,
        resources: Vec<crate::models::ListAnOrganizationSPaginatedTeams200ResponseResourcesInner>,
    ) -> ListAnOrganizationSPaginatedTeams200Response {
        ListAnOrganizationSPaginatedTeams200Response {
            schemas: None,
            total_results,
            items_per_page,
            start_index,
            resources,
        }
    }
}
