/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAProjectSIssues200ResponseInnerMetadataOneOf {
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl ListAProjectSIssues200ResponseInnerMetadataOneOf {
    pub fn new(filename: String, r#type: String, value: String) -> ListAProjectSIssues200ResponseInnerMetadataOneOf {
        ListAProjectSIssues200ResponseInnerMetadataOneOf {
            filename,
            r#type,
            value,
        }
    }
}


