/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAnOrganizationSUsers200ResponseInnerFlags {
    #[serde(rename = "sso: linked", skip_serializing_if = "Option::is_none")]
    pub sso_colon__linked: Option<bool>,
    #[serde(rename = "sso: invalid", skip_serializing_if = "Option::is_none")]
    pub sso_colon__invalid: Option<bool>,
}

impl ListAnOrganizationSUsers200ResponseInnerFlags {
    pub fn new() -> ListAnOrganizationSUsers200ResponseInnerFlags {
        ListAnOrganizationSUsers200ResponseInnerFlags {
            sso_colon__linked: None,
            sso_colon__invalid: None,
        }
    }
}
