/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListARepositorySCommits200ResponseInner {
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "message", deserialize_with = "Option::deserialize")]
    pub message: Option<String>,
}

impl ListARepositorySCommits200ResponseInner {
    pub fn new(
        date_created: String,
        id: String,
        message: Option<String>,
    ) -> ListARepositorySCommits200ResponseInner {
        ListARepositorySCommits200ResponseInner {
            date_created,
            id,
            message,
        }
    }
}
