/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListATagSValues200ResponseInner {
    #[serde(rename = "name")]
    pub name: String,
}

impl ListATagSValues200ResponseInner {
    pub fn new(name: String) -> ListATagSValues200ResponseInner {
        ListATagSValues200ResponseInner { name }
    }
}
