/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAnOrganizationSUsers200ResponseInnerUserEmailsInner {
    #[serde(rename = "is_verified", skip_serializing_if = "Option::is_none")]
    pub is_verified: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
}

impl ListAnOrganizationSUsers200ResponseInnerUserEmailsInner {
    pub fn new() -> ListAnOrganizationSUsers200ResponseInnerUserEmailsInner {
        ListAnOrganizationSUsers200ResponseInnerUserEmailsInner {
            is_verified: None,
            id: None,
            email: None,
        }
    }
}
