/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAnOrganizationSRepositories200ResponseInner {
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl ListAnOrganizationSRepositories200ResponseInner {
    pub fn new(date_created: String, id: String, name: String) -> ListAnOrganizationSRepositories200ResponseInner {
        ListAnOrganizationSRepositories200ResponseInner {
            date_created,
            id,
            name,
        }
    }
}


