/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAnOrganizationSTeams200ResponseInnerAvatar {
    #[serde(rename = "avatarType", skip_serializing_if = "Option::is_none")]
    pub avatar_type: Option<String>,
    #[serde(
        rename = "avatarUuid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub avatar_uuid: Option<Option<String>>,
}

impl ListAnOrganizationSTeams200ResponseInnerAvatar {
    pub fn new() -> ListAnOrganizationSTeams200ResponseInnerAvatar {
        ListAnOrganizationSTeams200ResponseInnerAvatar {
            avatar_type: None,
            avatar_uuid: None,
        }
    }
}
