/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAProjectSClientKeys200ResponseInnerDsn {
    #[serde(rename = "cdn")]
    pub cdn: String,
    #[serde(rename = "csp")]
    pub csp: String,
    #[serde(rename = "minidump")]
    pub minidump: String,
    #[serde(rename = "public")]
    pub public: String,
    #[serde(rename = "secret")]
    pub secret: String,
    #[serde(rename = "security")]
    pub security: String,
}

impl ListAProjectSClientKeys200ResponseInnerDsn {
    pub fn new(
        cdn: String,
        csp: String,
        minidump: String,
        public: String,
        secret: String,
        security: String,
    ) -> ListAProjectSClientKeys200ResponseInnerDsn {
        ListAProjectSClientKeys200ResponseInnerDsn {
            cdn,
            csp,
            minidump,
            public,
            secret,
            security,
        }
    }
}
