/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAProjectSUserFeedback200ResponseInnerEvent {
    #[serde(rename = "eventID", skip_serializing_if = "Option::is_none")]
    pub event_id: Option<String>,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
}

impl ListAProjectSUserFeedback200ResponseInnerEvent {
    pub fn new() -> ListAProjectSUserFeedback200ResponseInnerEvent {
        ListAProjectSUserFeedback200ResponseInnerEvent {
            event_id: None,
            id: None,
        }
    }
}


