/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAProjectSIssues200ResponseInnerProject {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}

impl ListAProjectSIssues200ResponseInnerProject {
    pub fn new() -> ListAProjectSIssues200ResponseInnerProject {
        ListAProjectSIssues200ResponseInnerProject {
            id: None,
            name: None,
            slug: None,
        }
    }
}
