/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListATeamSProjects200ResponseInnerTeam {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
}

impl ListATeamSProjects200ResponseInnerTeam {
    pub fn new(id: String, name: String, slug: String) -> ListATeamSProjects200ResponseInnerTeam {
        ListATeamSProjects200ResponseInnerTeam {
            id,
            name,
            slug,
        }
    }
}


