/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAProjectSEvents200ResponseInnerTagsInner {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl ListAProjectSEvents200ResponseInnerTagsInner {
    pub fn new() -> ListAProjectSEvents200ResponseInnerTagsInner {
        ListAProjectSEvents200ResponseInnerTagsInner {
            value: None,
            key: None,
        }
    }
}
