/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAProjectSClientKeys200ResponseInnerBrowserSdk {
    #[serde(rename = "choices", skip_serializing_if = "Option::is_none")]
    pub choices: Option<Vec<Vec<String>>>,
}

impl ListAProjectSClientKeys200ResponseInnerBrowserSdk {
    pub fn new() -> ListAProjectSClientKeys200ResponseInnerBrowserSdk {
        ListAProjectSClientKeys200ResponseInnerBrowserSdk {
            choices: None,
        }
    }
}


