/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListATagSValuesRelatedToAnIssue200ResponseInner {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl ListATagSValuesRelatedToAnIssue200ResponseInner {
    pub fn new(key: String, value: String) -> ListATagSValuesRelatedToAnIssue200ResponseInner {
        ListATagSValuesRelatedToAnIssue200ResponseInner {
            key,
            value,
        }
    }
}


