/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAProjectSIssues200ResponseInnerStats {
    #[serde(rename = "24h", skip_serializing_if = "Option::is_none")]
    pub param_24h: Option<Vec<Vec<f32>>>,
}

impl ListAProjectSIssues200ResponseInnerStats {
    pub fn new() -> ListAProjectSIssues200ResponseInnerStats {
        ListAProjectSIssues200ResponseInnerStats { param_24h: None }
    }
}
