/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListATeamSProjects200ResponseInner {
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(rename = "features")]
    pub features: Vec<String>,
    #[serde(rename = "firstEvent", deserialize_with = "Option::deserialize")]
    pub first_event: Option<String>,
    #[serde(rename = "hasAccess")]
    pub has_access: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "isBookmarked")]
    pub is_bookmarked: bool,
    #[serde(rename = "isMember")]
    pub is_member: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "platform", deserialize_with = "Option::deserialize")]
    pub platform: Option<String>,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "team")]
    pub team: Box<crate::models::ListATeamSProjects200ResponseInnerTeam>,
    #[serde(rename = "teams")]
    pub teams: Vec<crate::models::ListATeamSProjects200ResponseInnerTeam>,
    #[serde(rename = "latestDeploys", deserialize_with = "Option::deserialize")]
    pub latest_deploys: Option<String>,
}

impl ListATeamSProjects200ResponseInner {
    pub fn new(
        date_created: String,
        features: Vec<String>,
        first_event: Option<String>,
        has_access: bool,
        id: String,
        is_bookmarked: bool,
        is_member: bool,
        name: String,
        platform: Option<String>,
        slug: String,
        team: crate::models::ListATeamSProjects200ResponseInnerTeam,
        teams: Vec<crate::models::ListATeamSProjects200ResponseInnerTeam>,
        latest_deploys: Option<String>,
    ) -> ListATeamSProjects200ResponseInner {
        ListATeamSProjects200ResponseInner {
            date_created,
            features,
            first_event,
            has_access,
            id,
            is_bookmarked,
            is_member,
            name,
            platform,
            slug,
            team: Box::new(team),
            teams,
            latest_deploys,
        }
    }
}
