/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAnOrganizationSPaginatedTeams200ResponseResourcesInnerMeta {
    #[serde(rename = "resourceType", skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<String>,
}

impl ListAnOrganizationSPaginatedTeams200ResponseResourcesInnerMeta {
    pub fn new() -> ListAnOrganizationSPaginatedTeams200ResponseResourcesInnerMeta {
        ListAnOrganizationSPaginatedTeams200ResponseResourcesInnerMeta {
            resource_type: None,
        }
    }
}


