/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProvisionANewTeamRequest {
    #[serde(rename = "schemas")]
    pub schemas: Vec<String>,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<crate::models::ListAnOrganizationSPaginatedTeams200ResponseResourcesInnerMembersInner>>,
}

impl ProvisionANewTeamRequest {
    pub fn new(schemas: Vec<String>, display_name: String) -> ProvisionANewTeamRequest {
        ProvisionANewTeamRequest {
            schemas,
            display_name,
            members: None,
        }
    }
}


