/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAShortId200ResponseGroupSubscriptionDetails {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl ResolveAShortId200ResponseGroupSubscriptionDetails {
    pub fn new() -> ResolveAShortId200ResponseGroupSubscriptionDetails {
        ResolveAShortId200ResponseGroupSubscriptionDetails {
            reason: None,
        }
    }
}


