/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAnEventId200Response {
    #[serde(rename = "event")]
    pub event: Box<crate::models::ResolveAnEventId200ResponseEvent>,
    #[serde(rename = "eventId")]
    pub event_id: String,
    #[serde(rename = "groupId")]
    pub group_id: String,
    #[serde(rename = "organizationSlug")]
    pub organization_slug: String,
    #[serde(rename = "projectSlug")]
    pub project_slug: String,
}

impl ResolveAnEventId200Response {
    pub fn new(event: crate::models::ResolveAnEventId200ResponseEvent, event_id: String, group_id: String, organization_slug: String, project_slug: String) -> ResolveAnEventId200Response {
        ResolveAnEventId200Response {
            event: Box::new(event),
            event_id,
            group_id,
            organization_slug,
            project_slug,
        }
    }
}


