/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAShortId200Response {
    #[serde(rename = "organizationSlug")]
    pub organization_slug: String,
    #[serde(rename = "projectSlug")]
    pub project_slug: String,
    #[serde(rename = "shortId")]
    pub short_id: String,
    #[serde(rename = "group")]
    pub group: Box<crate::models::ResolveAShortId200ResponseGroup>,
    #[serde(rename = "groupId")]
    pub group_id: String,
}

impl ResolveAShortId200Response {
    pub fn new(organization_slug: String, project_slug: String, short_id: String, group: crate::models::ResolveAShortId200ResponseGroup, group_id: String) -> ResolveAShortId200Response {
        ResolveAShortId200Response {
            organization_slug,
            project_slug,
            short_id,
            group: Box::new(group),
            group_id,
        }
    }
}


