/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAnEventId200ResponseEventContextSession {
    #[serde(rename = "foo", skip_serializing_if = "Option::is_none")]
    pub foo: Option<String>,
}

impl ResolveAnEventId200ResponseEventContextSession {
    pub fn new() -> ResolveAnEventId200ResponseEventContextSession {
        ResolveAnEventId200ResponseEventContextSession {
            foo: None,
        }
    }
}


