/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAnEventId200ResponseEventEntriesInnerAnyOfData {
    #[serde(rename = "values")]
    pub values:
        Vec<crate::models::ResolveAnEventId200ResponseEventEntriesInnerAnyOfDataValuesInner>,
}

impl ResolveAnEventId200ResponseEventEntriesInnerAnyOfData {
    pub fn new(
        values: Vec<
            crate::models::ResolveAnEventId200ResponseEventEntriesInnerAnyOfDataValuesInner,
        >,
    ) -> ResolveAnEventId200ResponseEventEntriesInnerAnyOfData {
        ResolveAnEventId200ResponseEventEntriesInnerAnyOfData { values }
    }
}
