/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerMechanism {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "handled", skip_serializing_if = "Option::is_none")]
    pub handled: Option<bool>,
}

impl ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerMechanism {
    pub fn new() -> ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerMechanism {
        ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerMechanism {
            r#type: None,
            handled: None,
        }
    }
}


