/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAnEventId200ResponseEventEntriesInnerAnyOf2Data {
    #[serde(rename = "formatted")]
    pub formatted: String,
}

impl ResolveAnEventId200ResponseEventEntriesInnerAnyOf2Data {
    pub fn new(formatted: String) -> ResolveAnEventId200ResponseEventEntriesInnerAnyOf2Data {
        ResolveAnEventId200ResponseEventEntriesInnerAnyOf2Data { formatted }
    }
}
