/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerStacktraceFramesInner {
    #[serde(rename = "function")]
    pub function: String,
    #[serde(rename = "errors", deserialize_with = "Option::deserialize")]
    pub errors: Option<String>,
    #[serde(rename = "colNo", deserialize_with = "Option::deserialize")]
    pub col_no: Option<i32>,
    #[serde(rename = "vars", deserialize_with = "Option::deserialize")]
    pub vars: Option<serde_json::Value>,
    #[serde(rename = "package", deserialize_with = "Option::deserialize")]
    pub package: Option<String>,
    #[serde(rename = "absPath", deserialize_with = "Option::deserialize")]
    pub abs_path: Option<String>,
    #[serde(rename = "inApp")]
    pub in_app: bool,
    #[serde(rename = "lineNo")]
    pub line_no: i32,
    #[serde(rename = "module")]
    pub module: String,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "platform", deserialize_with = "Option::deserialize")]
    pub platform: Option<String>,
    #[serde(rename = "instructionAddr", deserialize_with = "Option::deserialize")]
    pub instruction_addr: Option<String>,
    #[serde(rename = "context")]
    pub context: Vec<Vec<crate::models::ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerStacktraceFramesInnerContextInnerInner>>,
    #[serde(rename = "symbolAddr", deserialize_with = "Option::deserialize")]
    pub symbol_addr: Option<String>,
    #[serde(rename = "trust", deserialize_with = "Option::deserialize")]
    pub trust: Option<String>,
    #[serde(rename = "symbol", deserialize_with = "Option::deserialize")]
    pub symbol: Option<String>,
}

impl ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerStacktraceFramesInner {
    pub fn new(
        function: String,
        errors: Option<String>,
        col_no: Option<i32>,
        vars: Option<serde_json::Value>,
        package: Option<String>,
        abs_path: Option<String>,
        in_app: bool,
        line_no: i32,
        module: String,
        filename: String,
        platform: Option<String>,
        instruction_addr: Option<String>,
        context: Vec<Vec<crate::models::ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerStacktraceFramesInnerContextInnerInner>>,
        symbol_addr: Option<String>,
        trust: Option<String>,
        symbol: Option<String>,
    ) -> ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerStacktraceFramesInner
    {
        ResolveAnEventId200ResponseEventEntriesInnerAnyOf3DataValuesInnerStacktraceFramesInner {
            function,
            errors,
            col_no,
            vars,
            package,
            abs_path,
            in_app,
            line_no,
            module,
            filename,
            platform,
            instruction_addr,
            context,
            symbol_addr,
            trust,
            symbol,
        }
    }
}
