/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAnEventId200ResponseEventUserData {
    #[serde(rename = "isStaff", skip_serializing_if = "Option::is_none")]
    pub is_staff: Option<bool>,
}

impl ResolveAnEventId200ResponseEventUserData {
    pub fn new() -> ResolveAnEventId200ResponseEventUserData {
        ResolveAnEventId200ResponseEventUserData { is_staff: None }
    }
}
