/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAnEventId200ResponseEventPackages {
    #[serde(rename = "my.package", skip_serializing_if = "Option::is_none")]
    pub my_period_package: Option<String>,
}

impl ResolveAnEventId200ResponseEventPackages {
    pub fn new() -> ResolveAnEventId200ResponseEventPackages {
        ResolveAnEventId200ResponseEventPackages {
            my_period_package: None,
        }
    }
}


