/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveAnEventId200ResponseEventEntriesInnerAnyOf1DataEnv {
    #[serde(rename = "ENV", skip_serializing_if = "Option::is_none")]
    pub env: Option<String>,
}

impl ResolveAnEventId200ResponseEventEntriesInnerAnyOf1DataEnv {
    pub fn new() -> ResolveAnEventId200ResponseEventEntriesInnerAnyOf1DataEnv {
        ResolveAnEventId200ResponseEventEntriesInnerAnyOf1DataEnv { env: None }
    }
}
