/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAnEventForAProject200ResponseMetadataOneOf1 {
    #[serde(rename = "title")]
    pub title: String,
}

impl RetrieveAnEventForAProject200ResponseMetadataOneOf1 {
    pub fn new(title: String) -> RetrieveAnEventForAProject200ResponseMetadataOneOf1 {
        RetrieveAnEventForAProject200ResponseMetadataOneOf1 { title }
    }
}
