/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

/// RetrieveReleaseHealthSessionStatistics200ResponseGroupsInner : A grouped result, as requested by the `groupBy` request parameter.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveReleaseHealthSessionStatistics200ResponseGroupsInner {
    /// These are key/value pairs, the key being the requested `groupBy` property with its corresponding value.
    #[serde(rename = "by")]
    pub by: serde_json::Value,
    /// These are key/value pairs, the key being the requested `field`, and the value the corresponding total over the requested time frame.
    #[serde(rename = "totals")]
    pub totals: serde_json::Value,
    /// These are key/value pairs, the key being the requested `field`, and the value is an array of aggregated values. The array corresponds to the times given in the `intervals` array.
    #[serde(rename = "series")]
    pub series: ::std::collections::HashMap<String, Vec<i32>>,
}

impl RetrieveReleaseHealthSessionStatistics200ResponseGroupsInner {
    /// A grouped result, as requested by the `groupBy` request parameter.
    pub fn new(by: serde_json::Value, totals: serde_json::Value, series: ::std::collections::HashMap<String, Vec<i32>>) -> RetrieveReleaseHealthSessionStatistics200ResponseGroupsInner {
        RetrieveReleaseHealthSessionStatistics200ResponseGroupsInner {
            by,
            totals,
            series,
        }
    }
}


