/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveTagDetails200Response {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "totalValues")]
    pub total_values: i32,
}

impl RetrieveTagDetails200Response {
    pub fn new(key: String, total_values: i32) -> RetrieveTagDetails200Response {
        RetrieveTagDetails200Response { key, total_values }
    }
}
