/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveATeam200ResponseOrganization {
    #[serde(rename = "avatar")]
    pub avatar: Box<crate::models::ListAnOrganizationSTeams200ResponseInnerAvatar>,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "isEarlyAdopter")]
    pub is_early_adopter: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "require2FA")]
    pub require2_fa: bool,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "status")]
    pub status: Box<crate::models::RetrieveATeam200ResponseOrganizationStatus>,
}

impl RetrieveATeam200ResponseOrganization {
    pub fn new(
        avatar: crate::models::ListAnOrganizationSTeams200ResponseInnerAvatar,
        date_created: String,
        id: String,
        is_early_adopter: bool,
        name: String,
        require2_fa: bool,
        slug: String,
        status: crate::models::RetrieveATeam200ResponseOrganizationStatus,
    ) -> RetrieveATeam200ResponseOrganization {
        RetrieveATeam200ResponseOrganization {
            avatar: Box::new(avatar),
            date_created,
            id,
            is_early_adopter,
            name,
            require2_fa,
            slug,
            status: Box::new(status),
        }
    }
}
