/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAnEventForAProject200ResponseMetadata {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "title")]
    pub title: String,
}

impl RetrieveAnEventForAProject200ResponseMetadata {
    pub fn new(r#type: String, value: String, title: String) -> RetrieveAnEventForAProject200ResponseMetadata {
        RetrieveAnEventForAProject200ResponseMetadata {
            r#type,
            value,
            title,
        }
    }
}


