/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAnEventForAProject200ResponseSdk {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl RetrieveAnEventForAProject200ResponseSdk {
    pub fn new() -> RetrieveAnEventForAProject200ResponseSdk {
        RetrieveAnEventForAProject200ResponseSdk {
            version: None,
            name: None,
        }
    }
}


