/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAnEventForAProject200ResponseMetadataOneOf {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl RetrieveAnEventForAProject200ResponseMetadataOneOf {
    pub fn new(r#type: String, value: String) -> RetrieveAnEventForAProject200ResponseMetadataOneOf {
        RetrieveAnEventForAProject200ResponseMetadataOneOf {
            r#type,
            value,
        }
    }
}


