/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAProject200ResponseLatestReleaseAuthorsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
}

impl RetrieveAProject200ResponseLatestReleaseAuthorsInner {
    pub fn new() -> RetrieveAProject200ResponseLatestReleaseAuthorsInner {
        RetrieveAProject200ResponseLatestReleaseAuthorsInner {
            name: None,
            email: None,
        }
    }
}
