/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAnOrganization200ResponseProjectsInnerTeamOneOfNot {}

impl RetrieveAnOrganization200ResponseProjectsInnerTeamOneOfNot {
    pub fn new() -> RetrieveAnOrganization200ResponseProjectsInnerTeamOneOfNot {
        RetrieveAnOrganization200ResponseProjectsInnerTeamOneOfNot {}
    }
}
