/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAProject200ResponsePluginsInnerAuthor {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl RetrieveAProject200ResponsePluginsInnerAuthor {
    pub fn new() -> RetrieveAProject200ResponsePluginsInnerAuthor {
        RetrieveAProject200ResponsePluginsInnerAuthor {
            name: None,
            url: None,
        }
    }
}
