/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf {
    #[serde(rename = "environment")]
    pub environment: String,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "dateStarted", deserialize_with = "Option::deserialize")]
    pub date_started: Option<String>,
    #[serde(rename = "dateFinished")]
    pub date_finished: String,
    #[serde(rename = "url", deserialize_with = "Option::deserialize")]
    pub url: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
}

impl RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf {
    pub fn new(environment: String, name: Option<String>, date_started: Option<String>, date_finished: String, url: Option<String>, id: String) -> RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf {
        RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf {
            environment,
            name,
            date_started,
            date_finished,
            url,
            id,
        }
    }
}


