/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveReleaseHealthSessionStatistics400Response {
    #[serde(rename = "detail")]
    pub detail: String,
}

impl RetrieveReleaseHealthSessionStatistics400Response {
    pub fn new(detail: String) -> RetrieveReleaseHealthSessionStatistics400Response {
        RetrieveReleaseHealthSessionStatistics400Response { detail }
    }
}
