/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAProject200ResponseLatestReleaseProjectsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}

impl RetrieveAProject200ResponseLatestReleaseProjectsInner {
    pub fn new() -> RetrieveAProject200ResponseLatestReleaseProjectsInner {
        RetrieveAProject200ResponseLatestReleaseProjectsInner {
            name: None,
            slug: None,
        }
    }
}
