/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitUserFeedbackRequest {
    /// The event ID. This can be retrieved from the [beforeSend callback](https://docs.sentry.io/platforms/javascript/configuration/filtering/#using-beforesend).
    #[serde(rename = "event_id")]
    pub event_id: String,
    /// User's name.
    #[serde(rename = "name")]
    pub name: String,
    /// User's email address.
    #[serde(rename = "email")]
    pub email: String,
    /// Comments supplied by user.
    #[serde(rename = "comments")]
    pub comments: String,
}

impl SubmitUserFeedbackRequest {
    pub fn new(
        event_id: String,
        name: String,
        email: String,
        comments: String,
    ) -> SubmitUserFeedbackRequest {
        SubmitUserFeedbackRequest {
            event_id,
            name,
            email,
            comments,
        }
    }
}
