/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateAClientKeyRequest {
    /// The new name for the client key.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl UpdateAClientKeyRequest {
    pub fn new() -> UpdateAClientKeyRequest {
        UpdateAClientKeyRequest { name: None }
    }
}
