/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateAProjectRequest {
    /// The new name for the project.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The new slug for the project.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The new platform for the project.
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    /// In case this API call is invoked with a user context this allows changing of the bookmark flag.
    #[serde(rename = "isBookmarked", skip_serializing_if = "Option::is_none")]
    pub is_bookmarked: Option<bool>,
    /// 
    #[serde(rename = "digestsMinDelay", skip_serializing_if = "Option::is_none")]
    pub digests_min_delay: Option<i32>,
    /// 
    #[serde(rename = "digestsMaxDelay", skip_serializing_if = "Option::is_none")]
    pub digests_max_delay: Option<i32>,
}

impl UpdateAProjectRequest {
    pub fn new() -> UpdateAProjectRequest {
        UpdateAProjectRequest {
            name: None,
            slug: None,
            platform: None,
            is_bookmarked: None,
            digests_min_delay: None,
            digests_max_delay: None,
        }
    }
}


