/*
 * API Reference
 *
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateAnOrganizationReleaseFileRequest {
    /// The new name (full path) of the file.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The new name of the dist.
    #[serde(rename = "dist", skip_serializing_if = "Option::is_none")]
    pub dist: Option<String>,
}

impl UpdateAnOrganizationReleaseFileRequest {
    pub fn new() -> UpdateAnOrganizationReleaseFileRequest {
        UpdateAnOrganizationReleaseFileRequest {
            name: None,
            dist: None,
        }
    }
}


